name: PersonalGitlabSync

on:
  push:
    branches: [ main, master ]
  delete:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - name: Push to GitLab Backup
      run: |
        GITLAB_URL="https://${{ secrets.TARGET_USERNAME }}:${{ secrets.TARGET_TOKEN }}@gitlab.com/${{ secrets.TARGET_USERNAME }}/lcsubmissions.git"
        git remote add gitlab "$GITLAB_URL"
        git push gitlab --mirror
